version: '2'
services:
  mitienda-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/mitienda/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mitienda
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
